allowBuilds:
  '@contentauth/c2pa-node': true
  '@openrouter/sdk': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma

overrides:
  kysely: "0.28.0"
